include: package:extra_pedantic/analysis_options.1.5.0.yaml

analyzer:
  errors:
    unused_import: error
  language:
    strict-raw-types: false

  exclude:
    - '**/app_localization.dart'
    - '**/*.config.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'
    - '**/*.g.dart'
    - '**/*.i69n.dart'
    - '**/*.mocks.dart'
    - '**/arch/dio_packages/**/*.dart'

linter:
  rules:
    avoid_types_as_parameter_names: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_field_initializers_in_const_classes: true
    avoid_redundant_argument_values: true
    avoid_renaming_method_parameters: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    camel_case_types: true
    camel_case_extensions: true
    omit_local_variable_types: true
    overridden_fields: true
    non_constant_identifier_names: true
    prefer_adjacent_string_concatenation: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: false
    prefer_single_quotes: true
    prefer_interpolation_to_compose_strings: true
    sort_constructors_first: false
    unnecessary_statements: true
    unnecessary_this: true
    unnecessary_new: true
    unnecessary_lambdas: true
    unnecessary_brace_in_string_interps: true
    use_key_in_widget_constructors: true
    sort_pub_dependencies: false
    strict_raw_type: false
    implicit_dynamic_type: false
    avoid_catches_without_on_clauses: false
