name: app_template
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  injectable: ^1.5.0
  get_it: ^7.2.0
  dio: ^4.0.4
  logger: ^1.1.0
  retry: ^3.1.0
  connectivity: ^3.0.6
  i69n: ^2.1.0
  auto_route: ^4.0.1
  flutter_gen: ^4.1.6
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0


  #icons
  weather_icons: ^3.0.0
  shared_preferences: ^2.0.13


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  flutter_gen_runner: ^4.1.6
  flutter_lints: ^1.0.0
  freezed: ^1.1.0
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.5
  bloc_test: ^9.0.1
  mockito: ^5.0.16
  extra_pedantic: ^1.5.0
  auto_route_generator: ^4.0.0

flutter_gen:
  integrations:
    flutter_svg: true


flutter:
  uses-material-design: true

  assets:
    - .env